"""Create wards table

Revision ID: dcfccb5e0e45
Revises: None
Create Date: 2026-08-08 15:02:35.704975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfccb5e0e45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ward_type', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wards_department'), 'wards', ['department'], unique=False)
    op.create_index(op.f('ix_wards_id'), 'wards', ['id'], unique=False)
    op.create_index(op.f('ix_wards_name'), 'wards', ['name'], unique=False)
    op.create_index(op.f('ix_wards_status'), 'wards', ['status'], unique=False)
    op.create_index(op.f('ix_wards_ward_type'), 'wards', ['ward_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wards_ward_type'), table_name='wards')
    op.drop_index(op.f('ix_wards_status'), table_name='wards')
    op.drop_index(op.f('ix_wards_name'), table_name='wards')
    op.drop_index(op.f('ix_wards_id'), table_name='wards')
    op.drop_index(op.f('ix_wards_department'), table_name='wards')
    op.drop_table('wards')
    # ### end Alembic commands ###
